### PR TITLE
Add seed file for users and assignments

### PR DESCRIPTION
**Pull request by wlffann**
This updates the seed file to create users and assign some other users
to them to be described.

[#142649211]

### CODE REVIEW

**Comment by kheppenstall** [comment]
@wlffann Thanks for remembering to do this! Would it also be possible to make the occasional assignment inactive?

**Comment by Dpalazzari** [comment]
@kheppenstall Ask and you shall receive.

**Comment by wlffann** [comment]
You got it!

**Comment by kheppenstall** [comment]
@wlffann @Dpalazzari Thank you! Merging in now.

**Pull request merged**
